@startuml simple_path

' 0
"Start" -->[1/16] "Start"
"Feld 1" -->[1/16] "Feld 1"
"Feld 2" -->[1/16] "Feld 2"
"Feld 3" -->[1/16] "Feld 3"
"Feld 4" -->[1/16] "Feld 4"
"Feld 5" -->[1/16] "Feld 5"
"Feld 6" -->[1/16] "Feld 6"
"Feld 7" -->[1/16] "Feld 7"
"Feld 8" -->[1/16] "Feld 8"
"Feld 9" -->[1/16] "Feld 9"
"Feld 10" -->[1/16] "Feld 10"
"Feld 11" -->[1/16] "Feld 11"
"Feld 12" -->[1/16] "Feld 12"
"Feld 13" -->[1/16] "Feld 13"
"Feld 14" -->[1/16] "Feld 14"

' 1
"Start" -->[1/4] "Feld 1"
-->[1/4] "Feld 2"
-->[1/4] "Feld 3"
-->[1/4] "Feld 4"
-->[1/4] "Feld 5"
-->[1/4] "Feld 6"
-->[1/4] "Feld 7"
-->[1/4] "Feld 8"
-->[1/4] "Feld 9"
-->[1/4] "Feld 10"
-->[1/4] "Feld 11"
-->[1/4] "Feld 12"
-->[1/4] "Feld 13"
-->[1/4] "Feld 14"
-->[1/4] "Ende"
-->[1] "Ende"

' 2
"Start" -->[3/8] "Feld 2"
"Feld 1"-->[3/8] "Feld 3"
"Feld 2"-->[3/8] "Feld 4"
"Feld 3"-->[3/8] "Feld 5"
"Feld 4"-->[3/8] "Feld 6"
"Feld 5"-->[3/8] "Feld 7"
"Feld 6"-->[3/8] "Feld 8"
"Feld 7"-->[3/8] "Feld 9"
"Feld 8"-->[3/8] "Feld 10"
"Feld 9"-->[3/8] "Feld 11"
"Feld 10"-->[3/8] "Feld 12"
"Feld 11"-->[3/8] "Feld 13"
"Feld 12"-->[3/8] "Feld 14"
"Feld 13"-->[3/8] "Ende"

' 3
"Start" -->[1/4]"Feld 3"
"Feld 1" -->[1/4]"Feld 4"
"Feld 2" -->[1/4]"Feld 5"
"Feld 3" -->[1/4]"Feld 6"
"Feld 4" -->[1/4]"Feld 7"
"Feld 5" -->[1/4]"Feld 8"
"Feld 6" -->[1/4]"Feld 9"
"Feld 7" -->[1/4]"Feld 10"
"Feld 8" -->[1/4]"Feld 11"
"Feld 9" -->[1/4]"Feld 12"
"Feld 10" -->[1/4]"Feld 13"
"Feld 11" -->[1/4]"Feld 14"
"Feld 12"-->[1/4]"Ende"

' 4
"Start" -->[1/16]"Feld 4"
"Feld 1" -->[1/16]"Feld 5"
"Feld 2" -->[1/16]"Feld 6"
"Feld 3" -->[1/16]"Feld 7"
"Feld 4" -->[1/16]"Feld 8"
"Feld 5" -->[1/16]"Feld 9"
"Feld 6" -->[1/16]"Feld 10"
"Feld 7" -->[1/16]"Feld 11"
"Feld 8" -->[1/16]"Feld 12"
"Feld 9" -->[1/16]"Feld 13"
"Feld 10" -->[1/16]"Feld 14"
"Feld 11" -->[1/16]"Ende"

@enduml